#!/usr/bin/env bash

# Install homebrew
#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zshrc $HOME/.zshrc

rm -rf $HOME/.gitconfig
ln -s $DOTFILES/gitconfig $HOME/.gitconfig
